string prompt

# Used to set options, empty by default:
# - 'register_person':      register the nearest person in the FOV and track him.
# - 'match_object':         match the detected objects to some target objects.
# - 'request_image':        include raw RGB and depth image in the response.
# - 'request_segments':     include segments for each object in the response.
# - 'find_pointed_object':  find the object being pointed at by the nearest person.
#
# Example: 'match_object|request_image|request_segments'
string flags
---
int32 status
string error_msg

std_msgs/Header header
int32 person_id

# Object[] objects

# Raw RGB image in BGR8 format, if 'request_image' flag is set.
sensor_msgs/Image rgb_image

# Raw depth image in 32FC1 format (in meters), if 'request_image' flag is set.
sensor_msgs/Image depth_image

# Segments of each object in 8UC1 format, if 'request_segments' flag is set.
sensor_msgs/Image[] segments